### ISSUE TITLE
Bins value do not make much sense

### ISSUE THREAD

**Issue by mattfack** [dbuscombe-usgs/pyDGS#11]
Dear Daniel, 
Dear pyDGS-community,

I am running DGS under windows10, with python 3.7.3.

The problem is: the percentile results do not make much sense. Attached you find the py file we use to process the picture, the picture itself and a txt file reporting the output dictionary we get. Just to give you an idea, the first items of the dictionary are as follows:

{'mean grain size': 22.825277309626294, 'grain size sorting': 15.48001614559779, 'grain size skewness': 0.013117130518621484, 'grain size kurtosis': 0.06579535694260326, 'percentiles': array([ 5, 10, 16, 25, 50, 75, 84, 90, 95]), 'percentile_values': array([5643.23250669, 5106.20793073, 4918.2709746 , 4808.84553027,
4713.62400891, 4682.30436367, 4675.62013302, 4671.91079554,
4669.17948268]),

While the mean gs seems reasonable (even though a bit small, compared to field measurements), the percentiles are in descending order (shouldn't it be ascending following the percentiles array order?) and are way to high.

What I cannot find on this github page (or on the internet in general :) ) are the following pieces of information:

1. Are the ouputs in mm or in pixels? (I assume that, given the resolution scale, the results are given in mm)
2. What is the real meaning of density?
3. If I have a picture with resolution 180 dpi, I assume the following conversion would work:
180 DPI = 180 PPI = 1/180 inch/pixel = 1/180*25.4 inch/pixel * mm/inch = 0.141 mm/pixel
4. What does the filter do?
5. Is the 'notes' parameter only linked to wavelet analysis, i.e. I can leave it as it is? It seems not to affect the results that much.
6. What is the maxscale? It seems to affect the results a lot!
7. Is there a way to print the gsd from whithin DGS?

Thanks to all who might help me!

Cheers

**Comment by ddbuscombe** [comment]
My apologies. This code has been modified for individual users' needs over the years and I have let it fall into a state of neglect. Please give me a few days to fix, test, and post a new version. Thanks

**Comment by mattfack** [comment]
Great, Daniel! 
Looking forward to it!
Cheers

**Comment by ddbuscombe** [comment]
Ok, first significant update since 2016. It was past time I updated this repo. 

I have posted a new version that is a major rewrite. Gone are all my old (2012!!) cython codes, replaced with the much better pywavelets package. Therefore, there is no longer a need to specify wavelet parameters, or density. Image filtering occurs by default, but it is a mild filter designed to remove only very high frequency (pixel scale) noise. `maxscale` is still there, but is better explained (I hope)

Outputs are in pixels if resolution=1, otherwise the units of output grain sizes are the same as your resolution. This is also now better explained. The updated `test.py` script shows a few different example uses. You should be able to adapt that script for your own needs

My tests show that it is stable on ubuntu linux, and provides reasonable results that I have checked against manual measurements of grain diameters. Please report any weird results! Please report any bugs

The conda environment specifies python 3.6, but you could change that in the provided `yml` file if you require a different version
